sudo: required
language: cpp
dist: focal
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y git autopoint libtool automake pkg-config gettext autoconf autotools-dev xsltproc scons build-essential
  - sudo apt-get install -qq -y libjsoncpp-dev libdb++-dev libsqlite3-dev libxml2-dev libxslt1-dev libpcre3-dev libcurl4-openssl-dev libmemcached-dev libevent-dev uuid-dev libboost-thread-dev libboost-filesystem-dev libboost-system-dev libhiredis-dev libmosquitto-dev libmosquittopp-dev
  - git clone https://github.com/wolfsoft/libdcl.git
  - cd libdcl && ./autogen.sh && ./configure --disable-gtk --disable-qt --disable-winapi --disable-doxygen-doc && make && sudo make install && cd ..
script:
  - ./autogen.sh
  - ./configure --disable-dbp_isapi --disable-dbp_mongo --disable-dbp_script && make && make check
