<?xml version="1.0"?>
<!DOCTYPE messages SYSTEM "../dtd/messages.dtd">

<messages lang="en" langname="English">
   <message name="dbpager">dbPager Server 3.0</message>
   <message name="homepage">dbPager Server Home Page</message>
   <message name="langavail">Available languages</message>
   <message name="toc">Contents</message>
   <message name="example">Example</message>
   <message name="source">Source</message>
   <message name="result">Result</message>
   <message name="tip">Tip</message>
   <message name="note">Note</message>
   <message name="caution">Caution</message>
   <message name="prev-chapter">Previous chapter</message>
   <message name="next-chapter">Next chapter</message>
   <message name="send-feedback">Got a question?</message>
   <message name="copyright">Copyright &#169; 2008-2010 Dennis Prochko &lt;wolfsoft@mail.ru&gt;</message>
</messages>
