<?xml version="1.0"?>
<!DOCTYPE messages SYSTEM "../dtd/messages.dtd">

<messages lang="ru" langname="Russian">
   <message name="dbpager">dbPager Server 3.0</message>
   <message name="homepage">Домашняя страница dbPager Server</message>
   <message name="langavail">Доступные языки</message>
   <message name="toc">Содержание</message>
   <message name="example">Пример</message>
   <message name="source">Исходный код</message>
   <message name="result">Результат</message>
   <message name="tip">Полезный совет</message>
   <message name="note">Замечание</message>
   <message name="caution">Внимание</message>
   <message name="prev-chapter">Предыдущий раздел</message>
   <message name="next-chapter">Следующий раздел</message>
   <message name="send-feedback">Есть вопрос?</message>
   <message name="copyright">Авторские права &#169; 2008-2010 Прочко Денис Владимирович &lt;wolfsoft@mail.ru&gt;</message>
</messages>
